"""add description

Revision ID: 37581ad4ca5e
Revises: 6bf73c254e92
Create Date: 2026-05-13 17:24:43.121395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37581ad4ca5e'
down_revision: Union[str, None] = '6bf73c254e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(), nullable=False, server_default="no"))
    # чтобы у новых не было
    op.alter_column('products', 'description', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
